"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _story_card from './story-card.bones.json'

registerBones({
  "story-card": _story_card,
})
